class_name StoryHalf
extends RefCounted

static func labels() -> Dictionary:
	return {
		"halftime": [
			VN.minute(45),
			VN.bg("locker"),
			VN.portrait(""),
			VN.say("Перерыв. Ноги гудят. Тренер ещё не зашёл."),
			VN.say("Счёт на табло — не характер. Характер — то, с кем ты сядешь сейчас."),
			VN.goto("ht_hub"),
		],
		"ht_hub": [
			VN.bg("locker"),
			VN.portrait(""),
			VN.choice([
				VN.opt("Сесть к Глоку.", "ht_glock", VN.flag_off("ht_glock")),
				VN.opt("Подойти к Пеню.", "ht_pen", VN.flag_off("ht_pen")),
				VN.opt("Сокол в наушниках.", "ht_sokol", VN.flag_off("ht_sokol")),
				VN.opt("Фото команды на шкафчике.", "ht_photo", VN.flag_off("ht_photo")),
				VN.opt("Закрыть глаза. Завод. 2002.", "memory_factory", VN.flag_off("ht_memory")),
				VN.opt("Виктор Семёнович заходит.", "ht_coach", VN.flag_off("ht_coach")),
				VN.opt("Второй тайм. Пора.", "second_half"),
			]),
		],
		"ht_glock": [
			VN.flag("ht_glock"),
			VN.portrait("glock"),
			VN.say("Колено. Я чувствую, что оно сейчас отвалится. Я не знаю, что делать.", "glock"),
			VN.choice([
				VN.opt("«Я прикрою. Ты играешь, я пашу».", "htg_cover"),
				VN.opt("«Серёга, скажи тренеру. Я не хочу, чтобы ты ломался».", "htg_truth"),
				VN.opt("Молча сесть рядом.", "htg_sit"),
				VN.opt("«Я тоже боюсь. Но я здесь».", "htg_fear"),
			]),
		],
		"htg_cover": [
			VN.if_goto(VN.ge("team_bond", 6), "htg_cover_ok"),
			VN.stat("team_bond", -1),
			VN.stat("fatigue", 1),
			VN.stat("anxiety", 1),
			VN.say("Не вечно же.", "glock"),
			VN.goto("htg_tail"),
		],
		"htg_cover_ok": [
			VN.stat("team_bond", 2),
			VN.stat("fatigue", -1),
			VN.stat("hope", 1),
			VN.flag("glock_cover"),
			VN.say("Ты единственный, кто меня понимает.", "glock"),
			VN.goto("htg_tail"),
		],
		"htg_truth": [
			VN.flag("glock_truth"),
			VN.if_goto(VN.ge("introspection", 6), "htg_truth_ok"),
			VN.stat("team_bond", -2),
			VN.stat("regret", 1),
			VN.say("Ты обещал молчать.", "glock"),
			VN.goto("htg_tail"),
		],
		"htg_truth_ok": [
			VN.stat("introspection", 2),
			VN.stat("anxiety", -1),
			VN.say("Может, прав.", "glock"),
			VN.goto("htg_tail"),
		],
		"htg_sit": [
			VN.stat("introspection", 1),
			VN.stat("team_bond", 1),
			VN.say("Дерево скамьи холодное. Этого хватает."),
			VN.goto("htg_tail"),
		],
		"htg_fear": [
			VN.if_goto(VN.ge("introspection", 5), "htg_fear_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Слова тают. Мазь пахнет громче."),
			VN.goto("htg_tail"),
		],
		"htg_fear_ok": [
			VN.stat("introspection", 2),
			VN.stat("team_bond", 1),
			VN.stat("hope", 1),
			VN.say("Он кивает. Больше ничего не надо."),
			VN.goto("htg_tail"),
		],
		"htg_tail": [
			VN.say("Капитан — не повязка. Это когда тебя слушают.", "glock"),
			VN.portrait(""),
			VN.goto("ht_hub"),
		],
		"ht_pen": [
			VN.flag("ht_pen"),
			VN.portrait("pen"),
			VN.say("Семья на экране. Не разговор — доказательство, что кто-то ждёт."),
			VN.say("Второй тайм не вывезу. Забьют. Я даже не уехал в Москву.", "pen"),
			VN.choice([
				VN.opt("«Москва — город. Ты — человек».", "htp_city"),
				VN.opt("«Помни паб. Кричи сейчас».", "htp_pub"),
				VN.opt("Молча уйти.", "htp_leave"),
				VN.opt("«Ты бы справился. Всегда».", "htp_always"),
			]),
		],
		"htp_city": [
			VN.if_goto(VN.ge("team_bond", 5), "htp_city_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Ты не понимаешь.", "pen"),
			VN.goto("ht_hub"),
		],
		"htp_city_ok": [
			VN.stat("team_bond", 1),
			VN.stat("fatigue", -1),
			VN.stat("hope", 1),
			VN.say("Глупо звучит. Ладно.", "pen"),
			VN.goto("ht_hub"),
		],
		"htp_pub": [
			VN.if_goto(VN.ge("introspection", 5), "htp_pub_ok"),
			VN.stat("introspection", -1),
			VN.stat("regret", 1),
			VN.say("Что ты несёшь.", "pen"),
			VN.goto("ht_hub"),
		],
		"htp_pub_ok": [
			VN.stat("introspection", 2),
			VN.stat("hope", 1),
			VN.say("I am a goalkeeper.", "pen"),
			VN.say("Тише, чем на поле. Честнее."),
			VN.goto("ht_hub"),
		],
		"htp_leave": [
			VN.stat("team_bond", -1),
			VN.say("Ты оставляешь его с телефоном. Как тогда в пабе — с плачем."),
			VN.goto("ht_hub"),
		],
		"htp_always": [
			VN.if_goto(VN.ge("team_bond", 5), "htp_always_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Молчит. Не то молчание."),
			VN.goto("ht_hub"),
		],
		"htp_always_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.say("Он молчит. Это почти спасибо."),
			VN.goto("ht_hub"),
		],
		"ht_sokol": [
			VN.flag("ht_sokol"),
			VN.portrait("sokol"),
			VN.say("Я хочу, чтобы меня заметили.", "sokol"),
			VN.say("Я забивал. Меня заметили. И что?", "sokol"),
			VN.choice([
				VN.opt("«Уйдёшь в большой клуб. Отдавай пасы».", "hts_pass"),
				VN.opt("«Я испортил сезоны. Не повтори».", "hts_seasons"),
				VN.opt("Уйти.", "hts_leave"),
				VN.opt("«Не знаешь, что будет. Наслаждайся».", "hts_enjoy"),
			]),
		],
		"hts_pass": [
			VN.if_goto(VN.ge("team_bond", 6), "hts_pass_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Ты просто старый.", "sokol"),
			VN.goto("ht_hub"),
		],
		"hts_pass_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.say("Ты прав.", "sokol"),
			VN.goto("ht_hub"),
		],
		"hts_seasons": [
			VN.if_goto(VN.ge("introspection", 6), "hts_seasons_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Завидуешь.", "sokol"),
			VN.goto("ht_hub"),
		],
		"hts_seasons_ok": [
			VN.stat("introspection", 2),
			VN.stat("regret", 1),
			VN.say("А ты жалеешь?", "sokol"),
			VN.say("Да. Ты не говоришь этого вслух. Он всё равно слышит."),
			VN.goto("ht_hub"),
		],
		"hts_leave": [
			VN.stat("team_bond", -1),
			VN.say("Наушники возвращаются. Молодость любит громкость."),
			VN.goto("ht_hub"),
		],
		"hts_enjoy": [
			VN.if_goto(VN.ge("introspection", 5), "hts_enjoy_ok"),
			VN.stat("introspection", -1),
			VN.stat("regret", 1),
			VN.say("Смеётся. Тебе смешно в другую сторону."),
			VN.goto("ht_hub"),
		],
		"hts_enjoy_ok": [
			VN.stat("introspection", 2),
			VN.stat("hope", 1),
			VN.say("Слова остаются. Он не надевает наушники сразу."),
			VN.goto("ht_hub"),
		],
		"ht_photo": [
			VN.flag("ht_photo"),
			VN.say("Фото команды. Десять лет назад. Кто-то ушёл, кто-то умер, кто-то просто пропал."),
			VN.say("Ты в центре. Повязка ещё на руке. Улыбка как у человека, который верит в следующий контракт."),
			VN.choice([
				VN.opt("Взять фото.", "htph_take"),
				VN.opt("Оставить.", "htph_leave"),
				VN.opt("В карман.", "htph_pocket"),
			]),
		],
		"htph_take": [
			VN.if_goto(VN.ge("introspection", 4), "htph_take_ok"),
			VN.stat("introspection", -1),
			VN.stat("regret", 1),
			VN.say("Чужой человек. Похож на тебя. Не ты."),
			VN.goto("ht_hub"),
		],
		"htph_take_ok": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.stat("hope", 1),
			VN.say("Тепло. Бумага теплее табло."),
			VN.goto("ht_hub"),
		],
		"htph_leave": [
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Пусть висит. Ты не музей."),
			VN.goto("ht_hub"),
		],
		"htph_pocket": [
			VN.stat("nostalgia", 1),
			VN.stat("hope", 1),
			VN.say("Кладёшь. Как будто можно унести состав."),
			VN.goto("ht_hub"),
		],
		"ht_coach": [
			VN.flag("ht_coach"),
			VN.portrait("coach"),
			VN.if_goto(VN.score_cmp("gt"), "htc_win"),
			VN.say("Это не счёт. Это ваш характер на табло. Бардин, ты — капитан. Сделай что-нибудь.", "coach"),
			VN.goto("htc_menu"),
		],
		"htc_win": [
			VN.say("Не расслабились. Река не останавливается, и соперник тоже.", "coach"),
			VN.goto("htc_menu"),
		],
		"htc_menu": [
			VN.choice([
				VN.opt("«Мы не проиграем».", "htc_promise"),
				VN.opt("В пол.", "htc_floor"),
				VN.opt("«Скажите это Глоку и Пеню. Не только мне».", "htc_them"),
			]),
		],
		"htc_promise": [
			VN.if_goto(VN.ge("team_bond", 6), "htc_promise_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Хватит слов. Десять минут — и снова свисток.", "coach"),
			VN.goto("ht_hub"),
		],
		"htc_promise_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.say("Хватит слов. Десять минут — и снова свисток.", "coach"),
			VN.goto("ht_hub"),
		],
		"htc_floor": [
			VN.stat("team_bond", -1),
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Молчишь. Ладно.", "coach"),
			VN.goto("ht_hub"),
		],
		"htc_them": [
			VN.stat("team_bond", 1),
			VN.stat("introspection", 1),
			VN.say("Я сказал всем. Ты просто ближе.", "coach"),
			VN.goto("ht_hub"),
		],
		"memory_factory": [
			VN.flag("ht_memory"),
			VN.bg("factory"),
			VN.say("Цех. Ржавые фермы. Железные ворота. Газета: 2002."),
			VN.say("Отец у окна. Тебе четырнадцать. Ящик. Мяч."),
			VN.say("Гул, который не спрашивает, кем ты станешь."),
			VN.portrait("bardin"),
			VN.say("Ты жалеешь? Вопрос не его — твой. Сейчас. С перерыва."),
			VN.choice([
				VN.opt("Спросить: «ты жалеешь?»", "mem_ask", VN.ge("introspection", 5)),
				VN.opt("«Я ухожу из футбола».", "mem_leave"),
				VN.opt("Обнять.", "mem_hug"),
				VN.opt("Ударить по воротам.", "mem_kick"),
			]),
		],
		"mem_ask": [
			VN.stat("introspection", 2),
			VN.stat("nostalgia", 1),
			VN.say("Завод жалеет. Я — работаю.", "father"),
			VN.goto("mem_tail"),
		],
		"mem_leave": [
			VN.stat("introspection", 1),
			VN.stat("team_bond", 1),
			VN.say("Он не смеётся. Хуже: кивает, как будто ждал."),
			VN.goto("mem_tail"),
		],
		"mem_hug": [
			VN.stat("introspection", 2),
			VN.say("Спецовка колючая. Пахнет железом и мылом."),
			VN.goto("mem_tail"),
		],
		"mem_kick": [
			VN.if_goto(VN.ge("endurance", 5), "mem_kick_ok"),
			VN.stat("fatigue", 1),
			VN.say("Мяч бьёт слабее памяти."),
			VN.goto("mem_tail"),
		],
		"mem_kick_ok": [
			VN.stat("endurance", 1),
			VN.stat("nostalgia", 1),
			VN.say("Лязг. Тот самый. Ты его сегодня уже слышал."),
			VN.goto("mem_tail"),
		],
		"mem_tail": [
			VN.say("Разобьёшь мяч, дурак.", "father"),
			VN.say("И улыбка. Ты берёшь её с собой во второй тайм. Больше взять нечего."),
			VN.portrait(""),
			VN.bg("locker"),
			VN.say("Раздевалка возвращается. Колени — тоже."),
			VN.goto("ht_hub"),
		],
	}
