class_name StoryFirst
extends RefCounted

static func labels() -> Dictionary:
	return {
		"first_half": [
			VN.hud(true),
			VN.minute(1),
			VN.bg("match1"),
			VN.portrait(""),
			VN.say("Западная трибуна закрыта. Река за воротами не спрашивает."),
			VN.say("Иногда матч начинается раньше свистка."),
			VN.say("Иногда — там, где никто не считает голы."),
			VN.minute(2),
			VN.bg("west"),
			VN.say("Гул. Пустая западная — как жизнь после футбола."),
			VN.say("Шестнадцать лет. Молодёжка. Тот же пустой стадион. «Я буду здесь играть.»"),
			VN.say("Не знал, что восемнадцать лет. Не знал, что деньги исчезнут быстрее карьеры."),
			VN.choice([
				VN.opt("Улыбнуться воспоминанию.", "fh_m2_smile"),
				VN.opt("Сосредоточиться на мяче.", "fh_m2_focus"),
				VN.opt("Посмотреть на пустую трибуну.", "fh_m2_stand"),
			]),
		],
		"fh_m2_smile": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.stat("hope", 1),
			VN.say("Улыбка короткая. Трава не замечает."),
			VN.goto("fh_m4"),
		],
		"fh_m2_focus": [
			VN.stat("composure", 1),
			VN.say("Мяч — единственное, что не задаёт вопросов."),
			VN.goto("fh_m4"),
		],
		"fh_m2_stand": [
			VN.stat("anxiety", 1),
			VN.stat("introspection", 1),
			VN.say("Леса. Три года. Ремонт, который никто не заканчивает."),
			VN.goto("fh_m4"),
		],
		"fh_m4": [
			VN.minute(4),
			VN.bg("pitch"),
			VN.portrait(""),
			VN.say("Мяч в штрафной. Ты выносишь куда попало. Железный лязг."),
			VN.say("Четырнадцать лет. Цех отца. Бьёшь по железным воротам."),
			VN.say("Разобьёшь мяч, дурак.", "father"),
			VN.say("И улыбка. Через год завод закроют. Ворота — на металлолом. Ты — следующее."),
			VN.choice([
				VN.opt("Вспомнить улыбку.", "fh_m4_smile"),
				VN.opt("Лязг. Думать, как забить.", "fh_m4_clang"),
				VN.opt("Ворота сдали в металлолом.", "fh_m4_scrap"),
			]),
		],
		"fh_m4_smile": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.stat("hope", 1),
			VN.say("Лязг становится почти нежным."),
			VN.goto("fh_m7"),
		],
		"fh_m4_clang": [
			VN.stat("aggression", 1),
			VN.say("Злость — тоже топливо. Грязное."),
			VN.goto("fh_m7"),
		],
		"fh_m4_scrap": [
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Ты следующее. Ты это знаешь. Ты всё равно бежишь."),
			VN.goto("fh_m7"),
		],
		"fh_m7": [
			VN.minute(7),
			VN.bg("match2"),
			VN.portrait("pen"),
			VN.say("Лёгкий удар. Слишком лёгкий."),
			VN.say("Пень на траве. Лицо в руках. Дрожит."),
			VN.score(0, 1),
			VN.say("0:1. Ты видишь в нём свой страх."),
			VN.say("Тридцать один. Перелом пальца. Лицо в руках. Пень сел рядом, молчал, потом сказал:"),
			VN.say("Вставай. Сыграем.", "pen"),
			VN.say("Ты умеешь только бежать. Не сидеть рядом."),
			VN.choice([
				VN.opt("Сесть рядом молча.", "fh_m7_sit"),
				VN.opt("Крикнуть: «ОЛЕГ, ВСТАВАЙ!»", "fh_m7_shout"),
				VN.opt("Стоять и ждать.", "fh_m7_wait"),
				VN.opt("Вспомнить, как он сидел с тобой.", "fh_m7_memory"),
			]),
		],
		"fh_m7_sit": [
			VN.if_goto(VN.ge("team_bond", 4), "fh_m7_sit_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Ты садишься. Он не встаёт. Секунда становится длинной."),
			VN.goto("fh_m11"),
		],
		"fh_m7_sit_ok": [
			VN.stat("team_bond", 1),
			VN.stat("anxiety", -1),
			VN.say("Ты садишься. Он не благодарит. Это не нужно."),
			VN.goto("fh_m11"),
		],
		"fh_m7_shout": [
			VN.stat("aggression", 1),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Голос рвёт воздух. Он встаёт, потому что крик — привычнее жалости."),
			VN.goto("fh_m11"),
		],
		"fh_m7_wait": [
			VN.stat("composure", -1),
			VN.stat("fatigue", 1),
			VN.stat("anxiety", 1),
			VN.say("Судья смотрит на часы. Ты — на свои руки."),
			VN.goto("fh_m11"),
		],
		"fh_m7_memory": [
			VN.if_goto(VN.ge("introspection", 5), "fh_m7_memory_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Ты садишься. Он не встаёт. Память не всегда работает как пас."),
			VN.goto("fh_m11"),
		],
		"fh_m7_memory_ok": [
			VN.stat("introspection", 2),
			VN.stat("team_bond", 1),
			VN.say("Ты садишься. Он встаёт. Круг закрывается не словами."),
			VN.goto("fh_m11"),
		],
		"fh_m11": [
			VN.minute(11),
			VN.bg("pitch"),
			VN.portrait(""),
			VN.say("Падаешь на спину. Небо. Корабль. Дракон."),
			VN.say("Девятнадцатилетний ты не видел ничего — только сетку."),
			VN.say("Трава у реки. Девушка из параллели."),
			VN.say("Ты никогда не умел мечтать, Бардин.", "wife"),
			VN.say("Уехала. Имени ты не знал. Или знал — и выбросил, как ненужный мяч."),
			VN.choice([
				VN.opt("Попытаться увидеть дракона.", "fh_m11_dragon"),
				VN.opt("Закрыть глаза и встать.", "fh_m11_up"),
				VN.opt("Лежать дольше.", "fh_m11_lie"),
				VN.opt("Вспомнить её имя.", "fh_m11_name"),
			]),
		],
		"fh_m11_dragon": [
			VN.stat("introspection", 2),
			VN.stat("nostalgia", 1),
			VN.say("Облако почти складывается. Почти."),
			VN.goto("fh_m14"),
		],
		"fh_m11_up": [
			VN.stat("endurance", 1),
			VN.stat("introspection", -1),
			VN.stat("fatigue", 1),
			VN.say("Поле не ждёт мечтателей."),
			VN.goto("fh_m14"),
		],
		"fh_m11_lie": [
			VN.if_goto(VN.ge("introspection", 4), "fh_m11_lie_ok"),
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Пустота. Только прожекторы."),
			VN.goto("fh_m14"),
		],
		"fh_m11_lie_ok": [
			VN.stat("introspection", 2),
			VN.stat("nostalgia", 1),
			VN.say("Дракон есть. Он был всегда. Ты просто не поднимал голову."),
			VN.goto("fh_m14"),
		],
		"fh_m11_name": [
			VN.if_goto(VN.ge("introspection", 6), "fh_m11_name_ok"),
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Не помнишь. Это тоже правда."),
			VN.goto("fh_m14"),
		],
		"fh_m11_name_ok": [
			VN.flag("flag_lena_named"),
			VN.stat("introspection", 2),
			VN.stat("hope", 1),
			VN.say("Лена."),
			VN.say("Имя только сейчас. Только здесь. Только если ты честен."),
			VN.goto("fh_m14"),
		],
		"fh_m14": [
			VN.minute(14),
			VN.bg("match_action"),
			VN.portrait("sokol"),
			VN.say("Финт Сокола. Теряет мяч. Соперники смеются. Ты десять лет назад."),
			VN.say("Двадцать пять. Финт у зеркала. Она: «Иди спать.» Не смотрит."),
			VN.say("Ты до сих пор не понял, что деньги и слава — не главное."),
			VN.choice([
				VN.opt("«Покажи финт в конце, когда устанут».", "fh_m14_tip"),
				VN.opt("Промолчать, отвернуться.", "fh_m14_quiet"),
				VN.opt("«НЕ ДУРАЧЬСЯ, ОТДАЙ ПАС!»", "fh_m14_shout"),
				VN.opt("Вспомнить зеркало и улыбнуться.", "fh_m14_mirror"),
			]),
		],
		"fh_m14_tip": [
			VN.stat("team_bond", 1),
			VN.say("Ок.", "sokol"),
			VN.goto("fh_m18"),
		],
		"fh_m14_quiet": [
			VN.stat("team_bond", -1),
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.say("Смех соперников короче, чем твоя память."),
			VN.goto("fh_m18"),
		],
		"fh_m14_shout": [
			VN.stat("aggression", 1),
			VN.stat("team_bond", -1),
			VN.say("Да слышу я.", "sokol"),
			VN.goto("fh_m18"),
		],
		"fh_m14_mirror": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.say("Улыбка кривая. Как тогда."),
			VN.goto("fh_m18"),
		],
		"fh_m18": [
			VN.minute(18),
			VN.bg("river"),
			VN.portrait("wife", "right"),
			VN.say("Женщина в жёлтом пальто. Не смотрит на поле — на реку."),
			VN.say("Одиночество стоит дороже билета."),
			VN.say("Я никогда не любила футбол. Я любила тебя.", "wife"),
			VN.say("Это было прощание. Через полгода ушла."),
			VN.choice([
				VN.opt("Посмотреть на реку.", "fh_m18_river"),
				VN.opt("Посмотреть на женщину.", "fh_m18_woman"),
				VN.opt("Вспомнить день, когда она ушла.", "fh_m18_left"),
			]),
		],
		"fh_m18_river": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.say("Река не спрашивает. Она вообще ничего не спрашивает."),
			VN.goto("fh_m21"),
		],
		"fh_m18_woman": [
			VN.stat("team_bond", 1),
			VN.say("Это не она. Или она. Жёлтое пальто — не доказательство."),
			VN.goto("fh_m21"),
		],
		"fh_m18_left": [
			VN.if_goto(VN.ge("introspection", 5), "fh_m18_left_ok"),
			VN.stat("introspection", 1),
			VN.stat("anxiety", 1),
			VN.say("Пустота. Ты был на сборах. Всегда был на сборах."),
			VN.goto("fh_m21"),
		],
		"fh_m18_left_ok": [
			VN.stat("introspection", 2),
			VN.stat("regret", 1),
			VN.say("Дверь закрылась тихо. Как контракт."),
			VN.goto("fh_m21"),
		],
		"fh_m21": [
			VN.minute(21),
			VN.bg("match_goal"),
			VN.portrait(""),
			VN.say("Бардин, давай, заслужи!", "crowd"),
			VN.say("Штрафной. Двадцать два года. «Если забьёшь — в основу». Мяч тогда ушёл выше."),
			VN.say("Назавтра тренера уволили. Важно было не попасть. Важно было бить."),
			VN.choice([
				VN.opt("Пробить сильно, как тогда.", "fh_m21_shoot"),
				VN.opt("Пас Глоку.", "fh_m21_pass"),
				VN.opt("Просто выбить вперёд.", "fh_m21_clear"),
				VN.opt("Вспомнить тренера, который смотрел.", "fh_m21_coach"),
			]),
		],
		"fh_m21_shoot": [
			VN.if_goto(VN.ge("composure", 7), "fh_m21_shoot_ok"),
			VN.stat("composure", -2),
			VN.stat("fatigue", 1),
			VN.stat("regret", 1),
			VN.say("Мимо. Иногда честность не получает награды."),
			VN.say("Воздух выходит из тебя вместе с мячом."),
			VN.goto("fh_m25"),
		],
		"fh_m21_shoot_ok": [
			VN.stat("composure", 2),
			VN.stat("hope", 1),
			VN.score(1, 0),
			VN.say("Есть. Гол — как выдох, который долго держали."),
			VN.say("1:1. Стадион взрывается — и сразу помнит, что трибуна закрыта."),
			VN.goto("fh_m25"),
		],
		"fh_m21_pass": [
			VN.stat("team_bond", 1),
			VN.say("Он бьёт. Мимо. Кивает тебе — не за гол, за пас."),
			VN.goto("fh_m25"),
		],
		"fh_m21_clear": [
			VN.stat("composure", -1),
			VN.stat("endurance", 1),
			VN.say("Передышка. Мяч уходит за линию. Мальчик на бровке уже держит другой."),
			VN.goto("fh_m25"),
		],
		"fh_m21_coach": [
			VN.if_goto(VN.ge("introspection", 5), "fh_m21_coach_ok"),
			VN.stat("introspection", -1),
			VN.stat("regret", 1),
			VN.say("Медлишь. Мяч уходит. Промах. Цель выбери правильную."),
			VN.goto("fh_m25"),
		],
		"fh_m21_coach_ok": [
			VN.stat("introspection", 2),
			VN.stat("composure", 2),
			VN.score(1, 0),
			VN.say("Улыбка. Удар. Гол."),
			VN.say("Сетка. Адреналин. Это не вернёт контракт."),
			VN.goto("fh_m25"),
		],
		"fh_m25": [
			VN.minute(25),
			VN.bg("pitch"),
			VN.portrait("pen"),
			VN.say("I AM A GOALKEEPER!", "pen"),
			VN.say("Орёт по-английски. Никто не понимает. Английский паб. Пьяный Пень. «Когда-нибудь на Уэмбли»."),
			VN.say("Трансфер сорвался из-за травмы. Ты смотрел, как он плачет. Ничего не сказал."),
			VN.choice([
				VN.opt("«Ты бы справился на Уэмбли».", "fh_m25_wembley"),
				VN.opt("Промолчать, улыбнуться про себя.", "fh_m25_smile"),
				VN.opt("Крикнуть ему ту же фразу по-английски.", "fh_m25_echo"),
				VN.opt("Вспомнить паб и улыбнуться.", "fh_m25_pub"),
			]),
		],
		"fh_m25_wembley": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.say("...", "pen"),
			VN.say("Он слышит. Даже если делает вид, что нет."),
			VN.goto("fh_m32"),
		],
		"fh_m25_smile": [
			VN.stat("introspection", 1),
			VN.stat("team_bond", -1),
			VN.say("Улыбка для себя — дешёвая щедрость."),
			VN.goto("fh_m32"),
		],
		"fh_m25_echo": [
			VN.stat("team_bond", 1),
			VN.stat("nostalgia", 1),
			VN.say("I AM A GOALKEEPER!", "bardin"),
			VN.say("Глупо. Нужно. Стадион не понимает. Вы двое — да."),
			VN.goto("fh_m32"),
		],
		"fh_m25_pub": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.say("Пиво тогда было теплее этой воды на бровке."),
			VN.goto("fh_m32"),
		],
		"fh_m32": [
			VN.minute(32),
			VN.bg("match3"),
			VN.portrait("glock"),
			VN.say("Удар по ногам Глока. Судья молчит. Глок корчится. Смотрит: не сдавай."),
			VN.say("Укол в колено. Ты держишь его руку. «Не отключайте, хочу слышать.» Врачи не слушают."),
			VN.say("Вернулся медленнее навсегда. Ты ничего не сказал тогда. Можешь сказать сейчас."),
			VN.choice([
				VN.opt("«ЭТО ФОЛ!»", "fh_m32_foul"),
				VN.opt("Поднять: «Как ты?»", "fh_m32_lift"),
				VN.opt("Делать вид, что ничего.", "fh_m32_ignore"),
				VN.opt("«Терпи. Я прикрою».", "fh_m32_cover"),
			]),
		],
		"fh_m32_foul": [
			VN.stat("aggression", 1),
			VN.stat("team_bond", -1),
			VN.say("Судья смотрит сквозь тебя. Как контракт."),
			VN.goto("fh_m36"),
		],
		"fh_m32_lift": [
			VN.stat("team_bond", 1),
			VN.stat("fatigue", -1),
			VN.say("Играем.", "glock"),
			VN.goto("fh_m36"),
		],
		"fh_m32_ignore": [
			VN.stat("team_bond", -1),
			VN.stat("regret", 1),
			VN.say("Молчание — тоже удар. Своих."),
			VN.goto("fh_m36"),
		],
		"fh_m32_cover": [
			VN.if_goto(VN.ge("team_bond", 6), "fh_m32_cover_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Он не слышит. Боль громче."),
			VN.goto("fh_m36"),
		],
		"fh_m32_cover_ok": [
			VN.stat("team_bond", 2),
			VN.stat("anxiety", -1),
			VN.flag("glock_cover"),
			VN.say("Капитан — не повязка.", "glock"),
			VN.goto("fh_m36"),
		],
		"fh_m36": [
			VN.minute(36),
			VN.bg("match4"),
			VN.portrait(""),
			VN.say("Свободная зона. Колени."),
			VN.say("Восемнадцать лет. Десять километров. «Лёгкие как у лошади»."),
			VN.say("Лёгкие те же. Колени другие."),
			VN.choice([
				VN.opt("Рвануть.", "fh_m36_sprint"),
				VN.opt("Короткий пас.", "fh_m36_pass"),
				VN.opt("Закричать от боли и бежать.", "fh_m36_pain"),
				VN.opt("Вспомнить бег в восемнадцать.", "fh_m36_memory"),
			]),
		],
		"fh_m36_sprint": [
			VN.if_goto(VN.ge("endurance", 7), "fh_m36_sprint_ok"),
			VN.stat("knee_pain", 2),
			VN.stat("fatigue", 2),
			VN.stat("anxiety", 1),
			VN.say("Колени горят. Рывок гаснет. Трава держит тебя дольше, чем надо."),
			VN.goto("fh_m40"),
		],
		"fh_m36_sprint_ok": [
			VN.stat("endurance", 2),
			VN.stat("hope", 1),
			VN.flag("sokol_goal"),
			VN.score(1, 0),
			VN.say("Прострел. Сокол. Гол."),
			VN.say("Обводка. Он проходит. Иногда жадность — это смелость."),
			VN.goto("fh_m40"),
		],
		"fh_m36_pass": [
			VN.stat("composure", 1),
			VN.stat("endurance", -1),
			VN.say("Умно. Не красиво. Ты больше не красивый."),
			VN.goto("fh_m40"),
		],
		"fh_m36_pain": [
			VN.stat("aggression", 1),
			VN.stat("fatigue", 1),
			VN.stat("composure", -1),
			VN.stat("knee_pain", 1),
			VN.say("Боль говорит. Ты не слушаешь. Как всегда."),
			VN.goto("fh_m40"),
		],
		"fh_m36_memory": [
			VN.if_goto(VN.ge("introspection", 5), "fh_m36_memory_ok"),
			VN.stat("introspection", -1),
			VN.stat("regret", 1),
			VN.say("Стоп. Тело не верит памяти."),
			VN.goto("fh_m40"),
		],
		"fh_m36_memory_ok": [
			VN.stat("introspection", 2),
			VN.stat("endurance", 1),
			VN.flag("sokol_goal"),
			VN.score(1, 0),
			VN.say("Улыбка. Бежишь. Прострел. Сокол замыкает."),
			VN.goto("fh_m40"),
		],
		"fh_m40": [
			VN.minute(40),
			VN.bg("street"),
			VN.portrait(""),
			VN.say("Мальчик. Лет восемь. Старые кеды, мяч. Ты через двадцать лет."),
			VN.say("Отец-судья. «Подай.» Ты падаешь."),
			VN.say("Держи крепче. Никогда не отпускай. Это твой мяч.", "father"),
			VN.say("Он говорил не о мяче."),
			VN.choice([
				VN.opt("Показать, как держать.", "fh_m40_show"),
				VN.opt("Улыбнуться и побежать.", "fh_m40_smile"),
				VN.opt("Отдать свой мяч.", "fh_m40_give"),
				VN.opt("«Никогда не отпускай».", "fh_m40_hold"),
			]),
		],
		"fh_m40_show": [
			VN.stat("team_bond", 1),
			VN.stat("nostalgia", 1),
			VN.say("Вот так?", "boy"),
			VN.say("Вот так."),
			VN.goto("fh_m43"),
		],
		"fh_m40_smile": [
			VN.stat("introspection", 1),
			VN.say("Улыбка — тоже пас. Он принимает."),
			VN.goto("fh_m43"),
		],
		"fh_m40_give": [
			VN.stat("team_bond", 1),
			VN.stat("hope", 1),
			VN.say("У тебя ещё есть. Пока есть."),
			VN.goto("fh_m43"),
		],
		"fh_m40_hold": [
			VN.if_goto(VN.ge("introspection", 5), "fh_m40_hold_ok"),
			VN.stat("introspection", -1),
			VN.stat("regret", 1),
			VN.say("Нет слов. Отец забрал их на вахту."),
			VN.goto("fh_m43"),
		],
		"fh_m40_hold_ok": [
			VN.stat("introspection", 2),
			VN.stat("hope", 1),
			VN.say("Никогда не отпускай.", "bardin"),
			VN.say("Мальчик кивает слишком серьёзно для восьми."),
			VN.goto("fh_m43"),
		],
		"fh_m43": [
			VN.minute(43),
			VN.bg("tunnel"),
			VN.portrait(""),
			VN.say("Свисток тайма. Тоннель."),
			VN.say("Граффити: «Бардин, ты лучший». Рядом: «Бардин, ты мусор»."),
			VN.say("Может, оба."),
			VN.choice([
				VN.opt("Стереть «мусор».", "fh_m43_erase"),
				VN.opt("Оставить.", "fh_m43_leave"),
				VN.opt("Мелом: «Я был».", "fh_m43_chalk"),
			]),
		],
		"fh_m43_erase": [
			VN.stat("aggression", 1),
			VN.stat("hope", 1),
			VN.say("Пальцы в пыли. Слово держится лучше краски."),
			VN.goto("halftime"),
		],
		"fh_m43_leave": [
			VN.stat("introspection", 1),
			VN.say("Пусть висит. Как баннер."),
			VN.goto("halftime"),
		],
		"fh_m43_chalk": [
			VN.stat("introspection", 2),
			VN.stat("nostalgia", 1),
			VN.say("Коротко. Честно. Не для них."),
			VN.goto("halftime"),
		],
	}
