class_name StorySecond
extends RefCounted

static func labels() -> Dictionary:
	return {
		"second_half": [
			VN.minute(46),
			VN.hud(true),
			VN.bg("match_mid"),
			VN.portrait(""),
			VN.say("Второй тайм. Ноги тяжелее памяти. Река за воротами всё та же."),
			VN.goto("sh_m48"),
		],
		"sh_m48": [
			VN.minute(48),
			VN.bg("river"),
			VN.portrait("glock"),
			VN.say("Глок смотрит на реку. Не на мяч."),
			VN.say("Ночь. Дешёвое пиво. «Стал бы рыбаком. Счастье не в деньгах. В реке.»"),
			VN.choice([
				VN.opt("Смотреть на реку.", "sh48_river"),
				VN.opt("Сжать зубы и побежать.", "sh48_run"),
				VN.opt("Улыбнуться Глоку.", "sh48_smile"),
			]),
		],
		"sh48_river": [
			VN.stat("introspection", 2),
			VN.stat("nostalgia", 1),
			VN.say("Ты был мячом, не рекой."),
			VN.goto("sh48_tail"),
		],
		"sh48_run": [
			VN.stat("endurance", 2),
			VN.stat("aggression", 1),
			VN.stat("fatigue", 1),
			VN.say("Бег — твой единственный язык."),
			VN.goto("sh48_tail"),
		],
		"sh48_smile": [
			VN.stat("team_bond", 1),
			VN.stat("hope", 1),
			VN.say("Он не отвечает улыбкой. Отвечает тем, что остаётся на ногах."),
			VN.goto("sh48_tail"),
		],
		"sh48_tail": [
			VN.portrait(""),
			VN.say("Река не спрашивает. Ты всё ещё спрашиваешь."),
			VN.goto("sh_m53"),
		],
		"sh_m53": [
			VN.minute(53),
			VN.bg("match_action"),
			VN.portrait("sokol"),
			VN.say("Сокол мажет один на один."),
			VN.say("Тренер когда-то: ты боишься, что гол будет последним. Боялся пустоты после."),
			VN.choice([
				VN.opt("«Я тоже мазал. Просто бей».", "sh53_missed"),
				VN.opt("«ЗАБЕЙ, ДУРАК! ТЕБЕ ПЛАТЯТ!»", "sh53_pay"),
				VN.opt("Молчать.", "sh53_quiet"),
			]),
		],
		"sh53_missed": [
			VN.if_goto(VN.ge("team_bond", 7), "sh53_missed_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Не надо меня гладить.", "sokol"),
			VN.goto("sh_m58"),
		],
		"sh53_missed_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.say("Ок.", "sokol"),
			VN.goto("sh_m58"),
		],
		"sh53_pay": [
			VN.stat("aggression", 1),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Деньги. Слово пахнет ржавчиной."),
			VN.goto("sh_m58"),
		],
		"sh53_quiet": [
			VN.stat("team_bond", -1),
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Молчание после промаха — тоже промах."),
			VN.goto("sh_m58"),
		],
		"sh_m58": [
			VN.minute(58),
			VN.bg("pitch"),
			VN.portrait("pen"),
			VN.say("Пень лежит на спине. Крыша стадиона. Ему двадцать три в той памяти: лечь и не встать — свобода от контрактов."),
			VN.choice([
				VN.opt("Подбежать.", "sh58_run"),
				VN.opt("Не бежать.", "sh58_stay"),
				VN.opt("Лечь рядом.", "sh58_lie"),
			]),
		],
		"sh58_run": [
			VN.stat("team_bond", 1),
			VN.say("Ты над ним. Он видит тебя вверх ногами. Как жизнь."),
			VN.goto("sh_m63"),
		],
		"sh58_stay": [
			VN.stat("team_bond", -1),
			VN.stat("fatigue", 1),
			VN.say("Усталость выбирает за тебя."),
			VN.goto("sh_m63"),
		],
		"sh58_lie": [
			VN.if_goto(VN.ge("introspection", 5), "sh58_lie_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Трава колет шею. Дракона нет. Только прожекторы."),
			VN.goto("sh_m63"),
		],
		"sh58_lie_ok": [
			VN.stat("introspection", 2),
			VN.stat("hope", 1),
			VN.say("Небо. Наконец видишь дракона. Он был всегда."),
			VN.say_if(VN.flag_on("flag_lena_named"), "Лена бы сказала: вот, научился."),
			VN.goto("sh_m63"),
		],
		"sh_m63": [
			VN.minute(63),
			VN.bg("river"),
			VN.portrait(""),
			VN.say("Ветер с реки. Двадцать девять лет. Звонок жене: «ухожу из команды»."),
			VN.say("Деньги или счастье?", "wife"),
			VN.say("Вернулся через месяц. Она знала, что деньги не вернут."),
			VN.choice([
				VN.opt("Вдохнуть реку.", "sh63_breath"),
				VN.opt("Бежать быстрее.", "sh63_run"),
				VN.opt("Остановиться. Смотреть.", "sh63_stop"),
			]),
		],
		"sh63_breath": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.say("Мокрый воздух. Дешевле любого контракта."),
			VN.goto("sh_m68"),
		],
		"sh63_run": [
			VN.stat("endurance", 1),
			VN.stat("fatigue", 1),
			VN.say("Скорость как ответ. Плохой ответ. Единственный, который ты знаешь."),
			VN.goto("sh_m68"),
		],
		"sh63_stop": [
			VN.stat("introspection", 2),
			VN.say("Секунда без бега. Страшно. Честно."),
			VN.goto("sh_m68"),
		],
		"sh_m68": [
			VN.minute(68),
			VN.bg("match3"),
			VN.portrait("glock"),
			VN.say("Глок встаёт без гримасы. Колено опухло."),
			VN.say("Подвал, старые кресла, банка пива: буду сидеть на стадионе без денег — и буду счастлив."),
			VN.choice([
				VN.opt("«Держись, Серёга!»", "sh68_hold"),
				VN.opt("Пробежать мимо.", "sh68_past"),
				VN.opt("Обнять.", "sh68_hug"),
			]),
		],
		"sh68_hold": [
			VN.stat("team_bond", 1),
			VN.say("Играем.", "glock"),
			VN.goto("sh68_tail"),
		],
		"sh68_past": [
			VN.stat("team_bond", -1),
			VN.stat("fatigue", 1),
			VN.say("Страх выглядит как дисциплина."),
			VN.goto("sh68_tail"),
		],
		"sh68_hug": [
			VN.if_goto(VN.ge("team_bond", 5), "sh68_hug_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Он деревенеет. Рано. Или поздно."),
			VN.goto("sh68_tail"),
		],
		"sh68_hug_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.say("Коротко. Мужчины на поле обнимаются только после голов и перед концом."),
			VN.goto("sh68_tail"),
		],
		"sh68_tail": [
			VN.portrait(""),
			VN.say("Стадион помнит тебя. Ты помнишь мяч, деньги, страх. Это прощание, просто ещё без свистка."),
			VN.goto("sh_m72"),
		],
		"sh_m72": [
			VN.minute(72),
			VN.bg("match2"),
			VN.portrait(""),
			VN.say("Ошибка в своей зоне. Прибой не прощает."),
			VN.score(0, 1),
			VN.say("Мяч в сетке. В груди — тоже дыра."),
			VN.say("Двадцать лет. Тренер: сто вещей правильно. Не смотри на одну ошибку."),
			VN.choice([
				VN.opt("Забыть ошибку. Играть.", "sh72_forget"),
				VN.opt("Злиться на себя.", "sh72_rage"),
				VN.opt("Вспомнить тренера.", "sh72_coach"),
			]),
		],
		"sh72_forget": [
			VN.stat("composure", 2),
			VN.say("Холод возвращается. Тонкий. Нужный."),
			VN.goto("sh_m78"),
		],
		"sh72_rage": [
			VN.stat("aggression", 2),
			VN.stat("composure", -1),
			VN.stat("fatigue", 1),
			VN.if_goto(VN.gt("aggression", 4), "sh72_red"),
			VN.goto("sh_m78"),
		],
		"sh72_red": [
			VN.flag("red_card"),
			VN.say("Ты влетаешь в подкат. Поздно. Высоко."),
			VN.say("Красная. Тишина на трибунах."),
			VN.goto("ending_resolve"),
		],
		"sh72_coach": [
			VN.if_goto(VN.ge("introspection", 5), "sh72_coach_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Голос не приходит. Только свисток соперника."),
			VN.goto("sh_m78"),
		],
		"sh72_coach_ok": [
			VN.stat("introspection", 2),
			VN.stat("hope", 1),
			VN.say("Сто вещей. Одна дыра. Играй дальше."),
			VN.goto("sh_m78"),
		],
		"sh_m78": [
			VN.minute(78),
			VN.say("Проверка колена. Боль говорит: остановись. Ты не слушаешь."),
			VN.if_goto(VN.ge("knee_pain", 10), "sh_sub"),
			VN.choice([
				VN.opt("Затянуть бинт и идти.", "sh78_tape"),
				VN.opt("Сбавить. Доиграть умом.", "sh78_smart"),
			]),
		],
		"sh_sub": [
			VN.flag("substituted"),
			VN.goto("ending_resolve"),
		],
		"sh78_tape": [
			VN.stat("endurance", 1),
			VN.stat("knee_pain", 1),
			VN.stat("fatigue", 1),
			VN.say("Бинт врёт. Ты ему благодарен."),
			VN.goto("sh_m82"),
		],
		"sh78_smart": [
			VN.stat("composure", 1),
			VN.stat("fatigue", 1),
			VN.say("Ум — это тоже мышцы. Просто их не видно на баннере."),
			VN.goto("sh_m82"),
		],
		"sh_m82": [
			VN.minute(82),
			VN.bg("match_goal"),
			VN.portrait("sokol"),
			VN.say("Сокол на одиннадцатиметровой. Просят решить. Тебя."),
			VN.say("Двадцать четыре года. «Это ловушка». Отдал пас, проиграл, не попал в ловушку."),
			VN.choice([
				VN.opt("Пас Соколу.", "sh82_pass"),
				VN.opt("Бить самому.", "sh82_shoot"),
				VN.opt("Вспомнить тот пас и повторить.", "sh82_memory"),
			]),
		],
		"sh82_pass": [
			VN.if_goto(VN.ge("team_bond", 7), "sh82_pass_ok"),
			VN.stat("team_bond", -2),
			VN.stat("knee_pain", 1),
			VN.stat("fatigue", 2),
			VN.say("Потеря. Жёстко отбирают. Молодые проходят на скорости."),
			VN.goto("sh_m87"),
		],
		"sh82_pass_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.flag("sokol_goal"),
			VN.score(1, 0),
			VN.say("Гол.  Он орёт. Ты не орёшь. Ты был нужен для паса."),
			VN.goto("sh_m87"),
		],
		"sh82_shoot": [
			VN.if_goto(VN.ge("composure", 8), "sh82_shoot_ok"),
			VN.stat("composure", -2),
			VN.stat("knee_pain", 1),
			VN.stat("fatigue", 2),
			VN.say("Мимо. Промах. Стадион замер."),
			VN.say("Цель выбери правильную."),
			VN.goto("sh_m87"),
		],
		"sh82_shoot_ok": [
			VN.stat("composure", 2),
			VN.stat("hope", 1),
			VN.flag("bardin_goal"),
			VN.score(1, 0),
			VN.say("Гол. Твой. На колени. Не от боли — от того, что больше некуда."),
			VN.goto("sh_m87"),
		],
		"sh82_memory": [
			VN.if_goto(VN.ge("introspection", 6), "sh82_memory_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Медлишь. Мяч уходит. Передышка, которой ты не хотел."),
			VN.goto("sh_m87"),
		],
		"sh82_memory_ok": [
			VN.stat("introspection", 2),
			VN.stat("team_bond", 1),
			VN.flag("sokol_goal"),
			VN.score(1, 0),
			VN.say("Пас. Не ловушка. Гол Сокола. Ты улыбаешься чужому крику."),
			VN.goto("sh_m87"),
		],
		"sh_m87": [
			VN.minute(87),
			VN.bg("whistle"),
			VN.portrait(""),
			VN.say("Трое минут. Вокзал. Шестнадцать лет. Отец на вахту."),
			VN.say("Деньги не вернут время. Запомни.", "father"),
			VN.choice([
				VN.opt("Смотреть на часы.", "sh87_watch"),
				VN.opt("Не смотреть. Играть.", "sh87_play"),
				VN.opt("Закрыть глаза. Отец.", "sh87_father"),
			]),
		],
		"sh87_watch": [
			VN.stat("introspection", 1),
			VN.stat("nostalgia", 1),
			VN.say("Секунды дороже зарплаты."),
			VN.goto("sh_m90"),
		],
		"sh87_play": [
			VN.stat("endurance", 1),
			VN.stat("fatigue", 1),
			VN.say("Ты бежишь, потому что не умеешь не бежать."),
			VN.goto("sh_m90"),
		],
		"sh87_father": [
			VN.if_goto(VN.ge("introspection", 5), "sh87_father_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Темнота. Свисток уже где-то близко."),
			VN.goto("sh_m90"),
		],
		"sh87_father_ok": [
			VN.stat("introspection", 2),
			VN.stat("hope", 1),
			VN.say("Никогда не отпускай. Это твой мяч. Это не про мяч."),
			VN.goto("sh_m90"),
		],
		"sh_m90": [
			VN.minute(90),
			VN.bg("whistle"),
			VN.say("Финальный свисток. Счёт записан. История — ещё нет."),
			VN.say("Последний. Ты не знаешь, как жить без него."),
			VN.goto("ending_resolve"),
		],
	}
