class_name StoryEarly
extends RefCounted

static func labels() -> Dictionary:
	return {
		"intro": [
			VN.bg("cover"),
			VN.hud(false),
			VN.portrait(""),
			VN.say("Прибрежье. Стадион «Торпедо». Западная трибуна закрыта три года."),
			VN.say("Ты — Алексей Бардин. Тридцать четыре. Контракт кончается через месяц."),
			VN.say("Всё, что у тебя есть — раздевалка, бутсы и запах травы."),
			VN.say("Это не симулятор. Это девяносто минут, в которых заканчивается всё, чем ты был."),
			VN.goto("locker"),
		],
		"locker": [
			VN.bg("locker"),
			VN.say("Деревянная скамья. Бинты. Запах разогревающей мази."),
			VN.say("Глок режет тейпы, не глядя на руки. Пень в телефон — белый как мел."),
			VN.say("Сокол в наушниках отбивает ритм коленом. За стеной тренер орёт на судью из-за заявок."),
			VN.say("Дом — не квартира. Дом — эта раздевалка."),
			VN.say("Десять минут до выхода."),
			VN.goto("locker_hub"),
		],
		"locker_hub": [
			VN.bg("locker"),
			VN.portrait(""),
			VN.choice([
				VN.opt("Подойти к Виктору Семёновичу.", "locker_coach", VN.flag_off("talked_coach")),
				VN.opt("Посмотреть на бутсы.", "locker_boots", VN.flag_off("looked_boots")),
				VN.opt("Глянуть на расписание.", "locker_sched", VN.flag_off("looked_sched")),
				VN.opt("Вдохнуть этот запах.", "locker_smell", VN.flag_off("looked_smell")),
				VN.opt("Уйти молча. Колени это заметят.", "locker_skip", VN.flag_off("talked_coach")),
				VN.opt("Выйти на бровку.", "sideline", VN.OR([VN.flag_on("talked_coach"), VN.flag_on("skipped_coach")])),
			]),
		],
		"locker_boots": [
			VN.flag("looked_boots"),
			VN.portrait("bardin"),
			VN.say("Старые. Потёртые. Купил два года назад — тогда ещё казались дорогими. Сейчас копейки."),
			VN.say("Как и ты."),
			VN.say("Голос, который не просил разрешения: вы оба старые. И вас скоро выбросят."),
			VN.choice([
				VN.opt("Затянуть шнурки.", "locker_boots_tight"),
				VN.opt("Ослабить. Дать стопе воздух.", "locker_boots_loose"),
			]),
		],
		"locker_boots_tight": [
			VN.stat("endurance", 1),
			VN.stat("anxiety", 1),
			VN.say("Кожа скрипит. Узел держит. Ты делаешь вид, что этого достаточно."),
			VN.goto("locker_hub"),
		],
		"locker_boots_loose": [
			VN.stat("introspection", 1),
			VN.say("Пальцы гудят. Ты ещё не на поле, а уже торгуешься с болью."),
			VN.goto("locker_hub"),
		],
		"locker_sched": [
			VN.flag("looked_sched"),
			VN.say("Лист на стене. Имена. Галочки. На следующую неделю твоего имени в старте нет."),
			VN.say("Ничего не чувствуешь. Это хуже, чем если бы почувствовал."),
			VN.say("Ты не замечал денег. Не замечал, как уходишь сам. Жену — тоже."),
			VN.choice([
				VN.opt("Смотреть, пока буквы не размажутся.", "locker_sched_stare"),
				VN.opt("Отвернуться.", "locker_sched_away"),
			]),
		],
		"locker_sched_stare": [
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Бумага дешёвая. Как контракт."),
			VN.goto("locker_hub"),
		],
		"locker_sched_away": [
			VN.stat("anxiety", 1),
			VN.say("Спина знает список лучше глаз."),
			VN.goto("locker_hub"),
		],
		"locker_smell": [
			VN.flag("looked_smell"),
			VN.say("Пот. Мазь. Дерево. Мокрая трава откуда-то с коридора."),
			VN.say("Запах дома. Дом — раздевалка."),
			VN.say("Через десять лет это приснится. Ты заплачешь. И не вернёшься."),
			VN.choice([
				VN.opt("Запомнить.", "locker_smell_keep"),
				VN.opt("Отмахнуться. Некогда.", "locker_smell_wave"),
			]),
		],
		"locker_smell_keep": [
			VN.stat("nostalgia", 2),
			VN.stat("hope", 1),
			VN.flag("self_stay"),
			VN.say("Ты кладёшь запах туда, где раньше лежали деньги."),
			VN.goto("locker_hub"),
		],
		"locker_smell_wave": [
			VN.stat("fatigue", 1),
			VN.say("Рука сама тянется к бутсам. Привычка сильнее памяти."),
			VN.goto("locker_hub"),
		],
		"locker_coach": [
			VN.flag("talked_coach"),
			VN.portrait("coach"),
			VN.say("Виктор Семёнович. Шестьдесят два. Советский специалист. Называет тебя капитаном. Повязки нет уже год."),
			VN.say("Слушайте сюда. У некоторых из вас это последний матч. Я не буду говорить, у кого.", "coach"),
			VN.say("Бардин, ты — капитан. Сделай что-нибудь.", "coach"),
			VN.choice([
				VN.opt("Встать. «Мы не проиграем».", "locker_coach_stand"),
				VN.opt("Молчать. Смотреть в пол.", "locker_coach_silent"),
				VN.opt("«Мы не проиграем. Я обещаю».", "locker_coach_promise"),
			]),
		],
		"locker_coach_stand": [
			VN.if_goto(VN.ge("team_bond", 6), "locker_coach_stand_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Никто не смотрит. Голос падает в дерево скамьи."),
			VN.goto("locker_coach_stand_line"),
		],
		"locker_coach_stand_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.goto("locker_coach_stand_line"),
		],
		"locker_coach_stand_line": [
			VN.say("Хватит слов. Играйте так, чтобы запомнить.", "coach"),
			VN.goto("locker_coach_tail"),
		],
		"locker_coach_silent": [
			VN.stat("team_bond", -1),
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Молчишь. Ладно. Молчание тоже выбор.", "coach"),
			VN.goto("locker_coach_tail"),
		],
		"locker_coach_promise": [
			VN.if_goto(VN.ge("team_bond", 7), "locker_coach_promise_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Обещания на этом стадионе дешевые. Докажи на траве.", "coach"),
			VN.goto("locker_coach_tail"),
		],
		"locker_coach_promise_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 2),
			VN.say("Тогда докажи на траве.", "coach"),
			VN.goto("locker_coach_tail"),
		],
		"locker_coach_tail": [
			VN.portrait(""),
			VN.say("Глок уже бинтуется. Сокол в наушниках. Пень белый как мел."),
			VN.say("Выйди на бровку. Поговори с ними. Потом — свисток."),
			VN.goto("locker_hub"),
		],
		"locker_skip": [
			VN.flag("skipped_coach"),
			VN.stat("knee_pain", 1),
			VN.stat("regret", 1),
			VN.stat("team_bond", -1),
			VN.say("Можно не слушать тренера. Колени это заметят."),
			VN.say("Ты не пришёл. Это тоже выбор."),
			VN.say("Разминка не состоялась. Бровка всё равно ждёт."),
			VN.goto("sideline"),
		],
		"sideline": [
			VN.bg("street"),
			VN.portrait(""),
			VN.say("Бровка. Ветер с реки. Западная трибуна — леса, не катастрофа. Баннер «Бардин — легенда» ещё висит."),
			VN.say("Ты должен. Ты должен выйти. Ты должен с кем-то поговорить, пока свисток не сделал это за тебя."),
			VN.goto("sideline_hub"),
		],
		"sideline_hub": [
			VN.bg("street"),
			VN.portrait(""),
			VN.choice([
				VN.opt("Глок. Тейпы, колено, запах мази.", "sideline_glock", VN.flag_off("glock_talked")),
				VN.opt("Сокол. Наушники, ещё надеется.", "sideline_sokol", VN.flag_off("sokol_talked")),
				VN.opt("Постоять с собой. Бутсы износились.", "sideline_self", VN.flag_off("self_talked")),
				VN.opt("Глянуть на Пеня у ворот.", "sideline_pen", VN.any_flags(["glock_talked", "sokol_talked"])),
				VN.opt("Выходить. Хватит слов.", "first_half", VN.all_flags(["glock_talked", "sokol_talked", "self_talked"])),
				VN.opt("Выходить, не договорив.", "sideline_leave_early", VN.AND([
					VN.any_flags(["glock_talked", "sokol_talked", "self_talked"]),
					VN.NOT(VN.all_flags(["glock_talked", "sokol_talked", "self_talked"])),
				])),
			]),
		],
		"sideline_leave_early": [
			VN.stat("regret", 1),
			VN.goto("first_half"),
		],
		"sideline_glock": [
			VN.flag("glock_talked"),
			VN.portrait("glock"),
			VN.say("Сергей. Двадцать восемь. Правый защитник. Колено. Просит молчать."),
			VN.say("Бардин. Если сегодня Соболев меня уроет... ты прикроешь? Или я сам?", "glock"),
			VN.choice([
				VN.opt("Прикрою, не парься.", "sg_cover"),
				VN.opt("Скажи тренеру правду, Серёга.", "sg_truth"),
				VN.opt("Я тоже боюсь. Но я здесь.", "sg_fear"),
				VN.opt("Молчать. Смотреть на бутсы.", "sg_quiet"),
			]),
		],
		"sg_cover": [
			VN.if_goto(VN.sum_ge(["endurance", "team_bond"], 8), "sg_cover_ok"),
			VN.stat("team_bond", -1),
			VN.stat("knee_pain", 1),
			VN.stat("anxiety", 1),
			VN.say("Ты морщишься, затягивая в воздухе чужой бинт. Он это видит."),
			VN.say("Ладно. Я сам.", "glock"),
			VN.goto("sg_tail"),
		],
		"sg_cover_ok": [
			VN.stat("team_bond", 1),
			VN.stat("composure", 1),
			VN.flag("glock_cover"),
			VN.say("Ты единственный, кто меня понимает.", "glock"),
			VN.say("Капитан — не повязка. Это когда тебя слушают.", "glock"),
			VN.goto("sg_tail"),
		],
		"sg_truth": [
			VN.flag("glock_truth"),
			VN.if_goto(VN.ge("introspection", 6), "sg_truth_ok"),
			VN.stat("team_bond", -2),
			VN.stat("introspection", 1),
			VN.stat("regret", 1),
			VN.say("Ты же обещал молчать. Я думал, ты друг.", "glock"),
			VN.goto("sg_tail"),
		],
		"sg_truth_ok": [
			VN.stat("introspection", 1),
			VN.stat("knee_pain", -1),
			VN.say("Ты прав... но я не могу.", "glock"),
			VN.goto("sg_tail"),
		],
		"sg_fear": [
			VN.if_goto(VN.ge("introspection", 5), "sg_fear_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Слова тают в мази. Он отворачивается к полю."),
			VN.goto("sg_tail"),
		],
		"sg_fear_ok": [
			VN.stat("introspection", 2),
			VN.stat("team_bond", 1),
			VN.stat("hope", 1),
			VN.flag("glock_cover"),
			VN.say("Он смотрит. Кивает. Тишина говорит больше, чем слова."),
			VN.goto("sg_tail"),
		],
		"sg_quiet": [
			VN.stat("team_bond", -1),
			VN.stat("introspection", 1),
			VN.stat("knee_pain", 1),
			VN.stat("anxiety", 1),
			VN.stat("regret", 1),
			VN.say("Он замечает, как ты морщишься. Отворачивается."),
			VN.goto("sg_tail"),
		],
		"sg_tail": [
			VN.say("Если бы я не стал футболистом, я бы стал рыбаком. Просто сидеть у реки и ждать.", "glock"),
			VN.portrait(""),
			VN.goto("sideline_hub"),
		],
		"sideline_sokol": [
			VN.flag("sokol_talked"),
			VN.portrait("sokol"),
			VN.say("Девятнадцать. Нападающий. Финты, жадность, наушники. Ещё надеется."),
			VN.if_goto(VN.flag_on("glock_truth"), "ss_angry"),
			VN.say("Что? Я хочу забить. Хочу, чтобы меня заметили.", "sokol"),
			VN.goto("ss_menu"),
		],
		"ss_angry": [
			VN.say("Глок злой. Ты ему что-то сказал? Мне всё равно. Я хочу, чтобы меня заметили.", "sokol"),
			VN.goto("ss_menu"),
		],
		"ss_menu": [
			VN.say("Ну?", "sokol"),
			VN.choice([
				VN.opt("Уйдёшь в большой клуб. Не будь жадным. Отдавай пасы.", "ss_pass"),
				VN.opt("Я был таким же. Испортил несколько сезонов.", "ss_was"),
				VN.opt("Не дурачься. Отдай пас.", "ss_harsh"),
			]),
		],
		"ss_pass": [
			VN.if_goto(VN.ge("team_bond", 6), "ss_pass_ok"),
			VN.stat("team_bond", -1),
			VN.stat("anxiety", 1),
			VN.say("Ты просто старый.", "sokol"),
			VN.goto("ss_tail"),
		],
		"ss_pass_ok": [
			VN.stat("team_bond", 2),
			VN.stat("hope", 1),
			VN.say("Ты прав. Наверное.", "sokol"),
			VN.goto("ss_tail"),
		],
		"ss_was": [
			VN.if_goto(VN.ge("introspection", 6), "ss_was_ok"),
			VN.stat("introspection", -1),
			VN.stat("anxiety", 1),
			VN.say("Завидуешь.", "sokol"),
			VN.goto("ss_tail"),
		],
		"ss_was_ok": [
			VN.stat("introspection", 2),
			VN.stat("regret", 1),
			VN.say("А ты жалеешь?", "sokol"),
			VN.say("Ты не отвечаешь. Это и есть ответ."),
			VN.goto("ss_tail"),
		],
		"ss_harsh": [
			VN.stat("aggression", 1),
			VN.stat("team_bond", -1),
			VN.say("Ха.", "sokol"),
			VN.goto("ss_tail"),
		],
		"ss_tail": [
			VN.say("Он надевает наушники. Потом снимает."),
			VN.say("Иногда он слышит. Мир всё равно не ведёт таблицу честности."),
			VN.say("Цель выбери правильную. Я ещё не знаю, что это значит.", "sokol"),
			VN.portrait(""),
			VN.goto("sideline_hub"),
		],
		"sideline_self": [
			VN.flag("self_talked"),
			VN.portrait("bardin"),
			VN.say("Бутсы износились. Как и ты."),
			VN.say("Кто ты без футбола? Без денег? Без этой раздевалки?"),
			VN.choice([
				VN.opt("Запомнить запах. Запомнить реку. Не бежать.", "self_stay"),
				VN.opt("Затянуть шнурки и не думать.", "self_run"),
				VN.opt("Я не обязан быть удобным. Ни клубу, ни табло.", "self_hard"),
			]),
		],
		"self_stay": [
			VN.flag("self_stay"),
			VN.stat("introspection", 2),
			VN.stat("nostalgia", 1),
			VN.say("Река не спрашивает, куда течь. Ты всегда спрашивал. Сейчас ты смотришь."),
			VN.goto("sideline_hub"),
		],
		"self_run": [
			VN.flag("self_run"),
			VN.stat("endurance", 1),
			VN.stat("anxiety", 1),
			VN.say("Ты бежишь, потому что не умеешь не бежать."),
			VN.goto("sideline_hub"),
		],
		"self_hard": [
			VN.flag("self_hard"),
			VN.stat("composure", 1),
			VN.stat("aggression", 1),
			VN.say("Жёсткость — не то же самое, что правда. Но хотя бы не ложь."),
			VN.goto("sideline_hub"),
		],
		"sideline_pen": [
			VN.portrait("pen"),
			VN.say("Олег. Сорок. Вратарь. Уэмбли и Москва не случились."),
			VN.say("Он дрожит над бутылкой. Семья в телефоне — обои, не разговор."),
			VN.say("Ты видишь в нём свой страх. Ещё до свистка."),
			VN.choice([
				VN.opt("Постоять рядом, ничего не говоря.", "sp_stand"),
				VN.opt("Хлопнуть по плечу: «ты не один».", "sp_tap"),
				VN.opt("Оставить его. У тебя свои колени.", "sp_leave"),
			]),
		],
		"sp_stand": [
			VN.stat("team_bond", 1),
			VN.say("Он не смотрит. Но и не просит уйти."),
			VN.goto("sideline_hub"),
		],
		"sp_tap": [
			VN.if_goto(VN.ge("team_bond", 4), "sp_tap_ok"),
			VN.stat("anxiety", 1),
			VN.say("Слова падают мимо. Он уже в первом ударе, которого ещё нет."),
			VN.goto("sideline_hub"),
		],
		"sp_tap_ok": [
			VN.stat("team_bond", 1),
			VN.stat("hope", 1),
			VN.say("Знаю.", "pen"),
			VN.goto("sideline_hub"),
		],
		"sp_leave": [
			VN.stat("regret", 1),
			VN.say("Ты умеешь только бежать, не сидеть рядом."),
			VN.goto("sideline_hub"),
		],
	}
