class_name StoryEnd
extends RefCounted

static func labels() -> Dictionary:
	return {
		"ending_resolve": [
			VN.hud(false),
			VN.portrait(""),
			VN.if_goto(VN.flag_on("substituted"), "ending_a"),
			VN.if_goto(VN.flag_on("red_card"), "ending_d"),
			VN.if_goto(VN.AND([VN.flag_on("bardin_goal"), VN.score_cmp("gt")]), "ending_e"),
			VN.if_goto(VN.score_cmp("gt"), "ending_b"),
			VN.if_goto(VN.score_cmp("eq"), "ending_c"),
			VN.if_goto(VN.AND([VN.ge("regret", 6), VN.lt("hope", 4)]), "ending_f"),
			VN.goto("ending_g"),
		],
		"ending_a": [
			VN.setv("ending_id", "a"),
			VN.minute(78),
			VN.bg("pitch"),
			VN.say("Всё, Бардин. Выходи.", "doctor"),
			VN.portrait("glock"),
			VN.say("Ты знал, что так будет?", "glock"),
			VN.portrait(""),
			VN.if_goto(VN.gt("introspection", 6), "ending_a_hi"),
			VN.say("Ты не встал. Деньги ушли. Ты остался. Но тебя больше не было."),
			VN.goto("after_whistle"),
		],
		"ending_a_hi": [
			VN.say("Ты лёг на спину. Впервые в жизни ты не пытался встать. И это не было поражением."),
			VN.goto("after_whistle"),
		],
		"ending_b": [
			VN.setv("ending_id", "b"),
			VN.bg("match_goal"),
			VN.say("3:2 или сколько там — все бегут к Соколу. Ты идёшь медленнее."),
			VN.portrait("glock"),
			VN.say("Спасибо, брат.", "glock"),
			VN.portrait(""),
			VN.if_goto(VN.gt("introspection", 7), "ending_b_hi"),
			VN.if_goto(VN.gt("team_bond", 5), "ending_b_bond"),
			VN.say("Выиграл. Стадион уже был пуст. Просто ты не замечал."),
			VN.goto("after_whistle"),
		],
		"ending_b_hi": [
			VN.say("Ты выиграл. Ты был богат. Ты был беден. Но ты был здесь. И этого достаточно."),
			VN.goto("after_whistle"),
		],
		"ending_b_bond": [
			VN.say("Ты падаешь. Глок рядом. Ты не знал, что будет завтра. Знал этот стадион и этот ветер."),
			VN.goto("after_whistle"),
		],
		"ending_c": [
			VN.setv("ending_id", "c"),
			VN.bg("pitch"),
			VN.portrait("pen"),
			VN.say("Ничья. Вы с Пеньом на траве. Двое, которым некуда спешить."),
			VN.portrait(""),
			VN.if_goto(VN.gt("composure", 6), "ending_c_calm"),
			VN.if_goto(VN.gt("endurance", 7), "ending_c_body"),
			VN.say("Ты уходишь. Ты больше никогда не вернёшься. Стадион останется. Ты — нет."),
			VN.goto("after_whistle"),
		],
		"ending_c_calm": [
			VN.say("Ты смеёшься. Завтра этого не будет. Сегодня — было."),
			VN.goto("after_whistle"),
		],
		"ending_c_body": [
			VN.say("Небо. Ты сделал всё. Внутри пусто. Как всегда."),
			VN.goto("after_whistle"),
		],
		"ending_d": [
			VN.setv("ending_id", "d"),
			VN.bg("locker"),
			VN.say("Красная. Душ. Тишина, в которой слышно, как Сокол забивает без тебя."),
			VN.if_goto(VN.gt("aggression", 3), "ending_d_hit"),
			VN.say("Где-то в комнате для прессы орёт телевизор. Ты выключаешь. Деньги не вернутся. Игра не вернётся."),
			VN.goto("after_whistle"),
		],
		"ending_d_hit": [
			VN.say("Ты бьёшь шкафчик. Треснул. Как карьера. Но ты не жалел."),
			VN.goto("after_whistle"),
		],
		"ending_e": [
			VN.setv("ending_id", "e"),
			VN.bg("match_goal"),
			VN.say("Твой гол. Победный. Колени в траве. Не от боли."),
			VN.portrait("glock"),
			VN.if_goto(VN.gt("introspection", 7), "ending_e_hi"),
			VN.say("Почему ты не сказал?", "glock"),
			VN.say("Он пожимает плечами."),
			VN.say("Ты не знал, что играешь за двоих.", "glock"),
			VN.portrait(""),
			VN.goto("after_whistle"),
		],
		"ending_e_hi": [
			VN.say("Ты обнимаешь Глока."),
			VN.say("Главное — ты был рядом. Без денег. Без славы.", "bardin"),
			VN.portrait(""),
			VN.goto("after_whistle"),
		],
		"ending_f": [
			VN.setv("ending_id", "f"),
			VN.bg("west"),
			VN.say("Ты никто! Ты нищий!", "crowd"),
			VN.say("Голос с трибуны. Не обязательно знакомый. Обязательно точный."),
			VN.choice([
				VN.opt("Помахать.", "ending_f_wave"),
				VN.opt("Ответить.", "ending_f_answer"),
				VN.opt("Уйти.", "ending_f_leave"),
			]),
		],
		"ending_f_wave": [
			VN.stat("hope", 1),
			VN.say("Ты стал тем, кто просто играл."),
			VN.goto("after_whistle"),
		],
		"ending_f_answer": [
			VN.stat("introspection", 1),
			VN.say("Деньги — не главное.", "bardin"),
			VN.say("Смех. Или нет. Река не смеётся."),
			VN.goto("after_whistle"),
		],
		"ending_f_leave": [
			VN.stat("regret", 1),
			VN.say("Пустое будущее. Но своё."),
			VN.goto("after_whistle"),
		],
		"ending_g": [
			VN.setv("ending_id", "g"),
			VN.bg("river"),
			VN.say("Один на поле. Дождь. «Торпедо» гудит пустотой, как раковина."),
			VN.if_goto(VN.gt("introspection", 8), "ending_g_hi"),
			VN.say("Ты смотришь на руки. Они ничего не держат."),
			VN.say("Страшно было тогда — когда были деньги."),
			VN.goto("after_whistle"),
		],
		"ending_g_hi": [
			VN.say("Ты улыбаешься дождю. Деньги приходят и уходят. Ты остаёшься."),
			VN.goto("after_whistle"),
		],
		"after_whistle": [
			VN.bg("pitch"),
			VN.portrait(""),
			VN.if_goto(VN.score_cmp("gt"), "after_win"),
			VN.if_goto(VN.score_cmp("lt"), "after_loss"),
			VN.say("Свисток. Ничья. Сегодня было. Завтра этого не будет."),
			VN.goto("after_menu"),
		],
		"after_win": [
			VN.say("Свисток. Табло врёт так же, как деньги. Что ты скажешь себе?"),
			VN.goto("after_menu"),
		],
		"after_loss": [
			VN.say("Свисток. Счёт жёсткий. Ты уходишь. Куда?"),
			VN.goto("after_menu"),
		],
		"after_menu": [
			VN.choice([
				VN.opt("Я был здесь. Этого достаточно.", "after_here"),
				VN.opt("Не смотреть. Идти.", "after_go"),
				VN.opt("Деньги не вернут этот свисток.", "after_money"),
			]),
		],
		"after_here": [
			VN.setv("letter_to", "честно"),
			VN.say("Ты смотришь на реку. Она течёт. Ты не знаешь, куда течёшь ты."),
			VN.say("Мяч останется. И я останусь. Без славы. Просто я.", "bardin"),
			VN.goto("epilogue"),
		],
		"after_go": [
			VN.setv("letter_to", "уйти"),
			VN.say("Ты не оглядываешься. Ты не хочешь прощаться."),
			VN.say("Я умею молчать. Это я и уношу.", "bardin"),
			VN.goto("epilogue"),
		],
		"after_money": [
			VN.setv("letter_to", "жёстко"),
			VN.say("Ты смотришь на руки. Они ничего не держат."),
			VN.say("Страшно было тогда — когда были деньги.", "bardin"),
			VN.goto("epilogue"),
		],
		"epilogue": [
			VN.bg("apartment"),
			VN.portrait(""),
			VN.say("Новая квартира. Дешёвый линолеум. Обои в цветочек, как в общежитии."),
			VN.say("На столе — старый мяч."),
			VN.say("Новая игра — просто сидеть. Ты учишься."),
			VN.bg("epilogue"),
			VN.say("Ты пишешь письмо. Кому — не знаешь."),
			VN.say_if(VN.flag_on("self_stay"), "Ты хотя бы раз перестал бежать."),
			VN.say_if(VN.flag_on("self_run"), "Ты снова купил тишину в рассрочку."),
			VN.say_if(VN.flag_on("glock_cover"), "Ты был рядом. Без денег. Без славы. Просто два человека."),
			VN.say_if(VN.ge("anxiety", 6), "Страх будущего был рядом всё время."),
			VN.say_if(VN.flag_on("flag_lena_named"), "В углу письма — имя. Лена. Не адрес. Просто чтобы было."),
			VN.if_goto(VN.gt("introspection", 7), "epilogue_honest"),
			VN.say("«Не иду за мячом. Самое страшное и самое честное.»"),
			VN.goto("epilogue_river"),
		],
		"epilogue_honest": [
			VN.say("«Мяч останется. И я. Без денег. Без славы. Просто я. Этого достаточно.»"),
			VN.goto("epilogue_river"),
		],
		"epilogue_river": [
			VN.bg("river"),
			VN.if_goto(VN.gt("hope", 5), "epilogue_hope"),
			VN.say("Ты остановился. Она — нет. Это было концом."),
			VN.goto("credits"),
		],
		"epilogue_hope": [
			VN.say("Ты смотрел на реку. Она текла. Ты не знал, куда она течёт."),
			VN.say("Ты не знал, куда течёшь ты. Но ты знал, что вы течёте вместе."),
			VN.say("И это было началом."),
			VN.goto("credits"),
		],
		"credits": [
			VN.bg("cover"),
			VN.portrait(""),
			VN.hud(false),
			VN.say("90 МИНУТ"),
			VN.say("Алексей Бардин"),
			VN.say("Глок · Пень · Сокол"),
			VN.say("Виктор Семёнович"),
			VN.say("Прибрежье · «Торпедо»"),
			VN.say("Ты был здесь."),
		],
	}
